"""
Canonical list of RTS 22 transaction report fields.

Source: Commission Delegated Regulation (EU) 2017/590, Annex I, Table 2.
See docs/rts22_field_reference.md for full descriptions and notes.
"""

RTS22_FIELDS = [
    {"number": 1, "name": "report_status", "format": "NEWT/CANC"},
    {"number": 2, "name": "transaction_reference_number", "format": "ALPHANUM-52"},
    {"number": 3, "name": "trading_venue_transaction_id", "format": "ALPHANUM-52"},
    {"number": 4, "name": "executing_entity_id", "format": "LEI"},
    {"number": 5, "name": "investment_firm_covered_by_mifid", "format": "true/false"},
    {"number": 6, "name": "submitting_entity_id", "format": "LEI"},
    {"number": 7, "name": "buyer_id", "format": "LEI/MIC/NATIONAL_ID/INTC"},
    {"number": 8, "name": "buyer_branch_country", "format": "COUNTRYCODE_2"},
    {"number": 9, "name": "buyer_first_name", "format": "ALPHANUM-140"},
    {"number": 10, "name": "buyer_surname", "format": "ALPHANUM-140"},
    {"number": 11, "name": "buyer_date_of_birth", "format": "DATEFORMAT"},
    {"number": 12, "name": "buyer_decision_maker_id", "format": "LEI/NATIONAL_ID"},
    {"number": 13, "name": "buyer_decision_maker_first_name", "format": "ALPHANUM-140"},
    {"number": 14, "name": "buyer_decision_maker_surname", "format": "ALPHANUM-140"},
    {"number": 15, "name": "buyer_decision_maker_date_of_birth", "format": "DATEFORMAT"},
    {"number": 16, "name": "seller_id", "format": "LEI/MIC/NATIONAL_ID/INTC"},
    {"number": 17, "name": "seller_branch_country", "format": "COUNTRYCODE_2"},
    {"number": 18, "name": "seller_first_name", "format": "ALPHANUM-140"},
    {"number": 19, "name": "seller_surname", "format": "ALPHANUM-140"},
    {"number": 20, "name": "seller_date_of_birth", "format": "DATEFORMAT"},
    {"number": 21, "name": "seller_decision_maker_id", "format": "LEI/NATIONAL_ID"},
    {"number": 22, "name": "seller_decision_maker_first_name", "format": "ALPHANUM-140"},
    {"number": 23, "name": "seller_decision_maker_surname", "format": "ALPHANUM-140"},
    {"number": 24, "name": "seller_decision_maker_date_of_birth", "format": "DATEFORMAT"},
    {"number": 25, "name": "transmission_of_order_indicator", "format": "true/false"},
    {"number": 26, "name": "transmitting_firm_id_buyer", "format": "LEI"},
    {"number": 27, "name": "transmitting_firm_id_seller", "format": "LEI"},
    {"number": 28, "name": "trading_date_time", "format": "DATE_TIME_FORMAT"},
    {"number": 29, "name": "trading_capacity", "format": "DEAL/MTCH/AOTC"},
    {"number": 30, "name": "quantity", "format": "DECIMAL-18/17 or DECIMAL-18/5"},
    {"number": 31, "name": "quantity_currency", "format": "CURRENCYCODE_3"},
    {"number": 32, "name": "derivative_notional_change", "format": "INCR/DECR"},
    {"number": 33, "name": "price", "format": "DECIMAL / PNDG / NOAP"},
    {"number": 34, "name": "price_currency", "format": "CURRENCYCODE_3"},
    {"number": 35, "name": "net_amount", "format": "DECIMAL-18/5"},
    {"number": 36, "name": "venue", "format": "MIC"},
    {"number": 37, "name": "branch_membership_country", "format": "COUNTRYCODE_2"},
    {"number": 38, "name": "up_front_payment", "format": "DECIMAL-18/5"},
    {"number": 39, "name": "up_front_payment_currency", "format": "CURRENCYCODE_3"},
    {"number": 40, "name": "complex_trade_component_id", "format": "ALPHANUM-35"},
    {"number": 41, "name": "instrument_id", "format": "ISIN"},
    {"number": 42, "name": "instrument_full_name", "format": "ALPHANUM-350"},
    {"number": 43, "name": "instrument_classification", "format": "CFI_CODE"},
    {"number": 44, "name": "notional_currency_1", "format": "CURRENCYCODE_3"},
    {"number": 45, "name": "notional_currency_2", "format": "CURRENCYCODE_3"},
    {"number": 46, "name": "price_multiplier", "format": "DECIMAL-18/17"},
    {"number": 47, "name": "underlying_instrument_code", "format": "ISIN"},
    {"number": 48, "name": "underlying_index_name", "format": "INDEX/ALPHANUM-25"},
    {"number": 49, "name": "underlying_index_term", "format": "INTEGER-3 + DAYS/WEEK/MNTH/YEAR"},
    {"number": 50, "name": "option_type", "format": "PUTO/CALL/OTHR"},
    {"number": 51, "name": "strike_price", "format": "DECIMAL / PNDG"},
    {"number": 52, "name": "strike_price_currency", "format": "CURRENCYCODE_3"},
    {"number": 53, "name": "option_exercise_style", "format": "EURO/AMER/ASIA/BERM/OTHR"},
    {"number": 54, "name": "maturity_date", "format": "DATEFORMAT"},
    {"number": 55, "name": "expiry_date", "format": "DATEFORMAT"},
    {"number": 56, "name": "delivery_type", "format": "PHYS/CASH/OPTL"},
    {"number": 57, "name": "investment_decision_within_firm", "format": "NATIONAL_ID/ALPHANUM-50"},
    {"number": 58, "name": "investment_decision_branch_country", "format": "COUNTRYCODE_2"},
    {"number": 59, "name": "execution_within_firm", "format": "NATIONAL_ID/ALPHANUM-50"},
    {"number": 60, "name": "execution_branch_country", "format": "COUNTRYCODE_2"},
    {"number": 61, "name": "waiver_indicator", "format": "RFPT/NLIQ/OILQ/PRIC/SIZE/ILQD"},
    {"number": 62, "name": "short_selling_indicator", "format": "SESH/SSEX/SELL/UNDI"},
    {"number": 63, "name": "otc_post_trade_indicator", "format": "BENC/ACTX/LRGS/ILQD/SIZE/CANC/AMND/SDIV/RPRI/DUPL/TNCP/TPAC/XFPH"},
    {"number": 64, "name": "commodity_derivative_indicator", "format": "true/false"},
    {"number": 65, "name": "securities_financing_transaction_indicator", "format": "true/false"},
]